# Adatclip

In [2]:
import pandas as pd

df = pd.read_csv("/Users/taehayeong/Desktop/Git_workspace/AdaptCLIP/results/corruption_benchmark/adaptclip/visa/all/clean/class_metrics_visa_10seed_0shot.csv")
pd.options.display.float_format = '{:.2f}'.format
df

         class  I-AUROC  P-AUROC  P-AP  P-F1max
0       candle     0.87     0.99  0.22     0.36
1     capsules     0.94     0.94  0.33     0.44
2       cashew     0.86     0.94  0.23     0.28
3   chewinggum     0.97     0.99  0.83     0.78
4        fryum     0.92     0.95  0.26     0.34
5    macaroni1     0.83     0.98  0.16     0.23
6    macaroni2     0.72     0.98  0.02     0.06
7         pcb1     0.84     0.96  0.16     0.25
8         pcb2     0.66     0.93  0.12     0.20
9         pcb3     0.65     0.88  0.05     0.11
10        pcb4     0.97     0.95  0.32     0.37
11  pipe_fryum     0.97     0.98  0.44     0.53

In [3]:
df_gaussian = pd.read_csv("/Users/taehayeong/Desktop/Git_workspace/AdaptCLIP/results/corruption_benchmark/adaptclip/visa/all/gaussian_noise_s3/class_metrics_visa_10seed_0shot.csv")
df_gaussian

         class  I-AUROC  P-AUROC  P-AP  P-F1max
0       candle     0.73     0.95  0.15     0.27
1     capsules     0.89     0.94  0.27     0.39
2       cashew     0.81     0.96  0.31     0.37
3   chewinggum     0.93     0.99  0.75     0.72
4        fryum     0.86     0.96  0.32     0.40
5    macaroni1     0.88     0.97  0.18     0.27
6    macaroni2     0.66     0.97  0.01     0.04
7         pcb1     0.84     0.94  0.09     0.15
8         pcb2     0.62     0.93  0.12     0.19
9         pcb3     0.61     0.88  0.04     0.09
10        pcb4     0.96     0.95  0.31     0.38
11  pipe_fryum     0.95     0.98  0.47     0.51

In [4]:
num_cols = df.select_dtypes(include="number").columns

df_drop = df[["class"]].copy()
df_drop[num_cols] = (
    df[num_cols] - df_gaussian[num_cols]
).round(2)
df_drop

         class  I-AUROC  P-AUROC  P-AP  P-F1max
0       candle     0.14     0.03  0.07     0.09
1     capsules     0.05     0.00  0.06     0.06
2       cashew     0.05    -0.02 -0.08    -0.10
3   chewinggum     0.04     0.00  0.07     0.06
4        fryum     0.06    -0.01 -0.05    -0.06
5    macaroni1    -0.05     0.01 -0.02    -0.05
6    macaroni2     0.06     0.02  0.01     0.03
7         pcb1    -0.01     0.03  0.07     0.10
8         pcb2     0.04    -0.00  0.00     0.01
9         pcb3     0.04     0.00  0.01     0.01
10        pcb4     0.01     0.00  0.00    -0.01
11  pipe_fryum     0.02     0.00 -0.03     0.02

In [5]:
df_anomalyclip = pd.read_csv("/Users/taehayeong/Desktop/Git_workspace/AdaptCLIP/overleaf_tables/anomalyclip_visa_clean.csv")
df_anomalyclip
df_adaptclip = pd.read_csv("/Users/taehayeong/Desktop/Git_workspace/AdaptCLIP/overleaf_tables/adaptclip_visa_clean.csv")
df_adaptclip

         class  I-AUROC  P-AUROC  P-AP  P-F1max
0       candle     0.87     0.99  0.22     0.36
1     capsules     0.94     0.94  0.33     0.44
2       cashew     0.86     0.94  0.23     0.28
3   chewinggum     0.97     0.99  0.83     0.78
4        fryum     0.92     0.95  0.26     0.34
5    macaroni1     0.83     0.98  0.16     0.23
6    macaroni2     0.72     0.98  0.02     0.06
7         pcb1     0.84     0.96  0.16     0.25
8         pcb2     0.66     0.93  0.12     0.20
9         pcb3     0.65     0.88  0.05     0.11
10        pcb4     0.97     0.95  0.32     0.37
11  pipe_fryum     0.97     0.98  0.44     0.53

In [6]:
df_anomalyclip

         class  I-AUROC  P-AUROC  P-AP  P-F1max
0       candle     0.88     0.98  0.20     0.33
1     capsules     0.91     0.96  0.28     0.36
2       cashew     0.96     0.96  0.22     0.29
3   chewinggum     0.98     0.99  0.51     0.56
4        fryum     0.96     0.93  0.19     0.26
5    macaroni1     0.89     0.98  0.17     0.25
6    macaroni2     0.78     0.98  0.07     0.12
7         pcb1     0.91     0.94  0.09     0.15
8         pcb2     0.69     0.91  0.10     0.17
9         pcb3     0.77     0.86  0.05     0.13
10        pcb4     0.98     0.95  0.31     0.35
11  pipe_fryum     0.95     0.96  0.20     0.31

In [7]:
num_cols = df_adaptclip.select_dtypes(include="number").columns

df_drop = df_adaptclip[["class"]].copy()
df_drop[num_cols] = (
    df_adaptclip[num_cols] - df_anomalyclip[num_cols]
).round(2)
df_drop

         class  I-AUROC  P-AUROC  P-AP  P-F1max
0       candle    -0.01     0.01  0.02     0.03
1     capsules     0.03    -0.02  0.05     0.08
2       cashew    -0.10    -0.02  0.01    -0.01
3   chewinggum    -0.01     0.00  0.32     0.22
4        fryum    -0.04     0.02  0.07     0.08
5    macaroni1    -0.06     0.00 -0.01    -0.02
6    macaroni2    -0.06     0.00 -0.05    -0.06
7         pcb1    -0.07     0.02  0.07     0.10
8         pcb2    -0.03     0.02  0.02     0.03
9         pcb3    -0.12     0.02  0.00    -0.02
10        pcb4    -0.01     0.00  0.01     0.02
11  pipe_fryum     0.02     0.02  0.24     0.22

In [10]:
winclip = pd.read_csv("/Users/taehayeong/Desktop/Git_workspace/AdaptCLIP/results/target_failure_analysis/winclip/mvtec/transistor/clean/class_metrics_mvtec_10seed_0shot.csv")
winclip = winclip[["P-AUROC", "P-AP", "P-F1max"]]
winclip
adaptclip = df_adaptclip[["P-AUROC", "P-AP", "P-F1max"]]
anomalyclip = df_anomalyclip[["P-AUROC", "P-AP", "P-F1max"]]

In [11]:
winclip

   P-AUROC  P-AP  P-F1max
0     0.59  0.06     0.11

In [12]:
adaptclip

    P-AUROC  P-AP  P-F1max
0      0.99  0.22     0.36
1      0.94  0.33     0.44
2      0.94  0.23     0.28
3      0.99  0.83     0.78
4      0.95  0.26     0.34
5      0.98  0.16     0.23
6      0.98  0.02     0.06
7      0.96  0.16     0.25
8      0.93  0.12     0.20
9      0.88  0.05     0.11
10     0.95  0.32     0.37
11     0.98  0.44     0.53

In [ ]:
df5= pd.read_csv("/Users/taehayeong/Desktop/Git_workspace/AdaptCLIP/results/target_failure_analysis/summaries/target_hard_class_drop_compact_gaussian_noise_by_model.csv")
df5